asd

diff --git a/.github/workflows/main_web-api-thell-u3.yml b/.github/workflows/main_web-api-thell-u3.yml
--- a/.github/workflows/main_web-api-thell-u3.yml
+++ b/.github/workflows/main_web-api-thell-u3.yml
@@ -1,6 +1,9 @@
 # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 # More GitHub Actions for Azure: https://github.com/Azure/actions
 
+# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
+# More GitHub Actions for Azure: https://github.com/Azure/actions
+
 name: Build and deploy ASP.Net Core app to Azure Web App - web-api-thell-u3
 
 on:
@@ -62,17 +65,18 @@ jobs:
           app-name: 'web-api-thell-u3'
           slot-name: 'Production'
           package: .
-  test:
-    runs-on: ubuntu-latest
-    needs: deploy
-    steps:
-      - name: Run smoke test
-        run: |
-          echo "Running smoke test..."
-          response=$(curl -s -o /dev/null -w "%{http_code}" https://web-api-thell-u3-smoketest.azurewebsites.net/api/SmokeTest)
-          if [ "$response" != "200" ]; then
-            echo "Smoke test failed with status: $response"
-            exit 1
-          fi
-          echo "Smoke test passed!"
+          
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs: deploy
+  #   steps:
+  #     - name: Run smoke test
+  #       run: |
+  #         echo "Running smoke test..."
+  #         response=$(curl -s -o /dev/null -w "%{http_code}" https://web-api-thell-u3-smoketest.azurewebsites.net/api/SmokeTest)
+  #         if [ "$response" != "200" ]; then
+  #           echo "Smoke test failed with status: $response"
+  #           exit 1
+  #         fi
+  #         echo "Smoke test passed!"
           
